In [6]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

In [7]:
face_cascade = cv2.CascadeClassifier('face.xml')
eye_cascade = cv2.CascadeClassifier('eye.xml')
model = load_model('model.h5')

In [8]:
mixer.init()
sound= mixer.Sound('alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=3)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,255,0), thickness=2 )
        
        # preprocessing steps
            eye= frame[ey:ey+eh,ex:ex+ew]
            eye= cv2.resize(eye,(80,80))
            eye= eye/255
            eye= eye.reshape(80,80,3)
            eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
            prediction = model.predict(eye)
            print(prediction)
       
        # if eyes are closed
        if prediction[0][0]>0.30:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.90:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-5
            if (Score<10 or Score>25):
                Score=0
            
         
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[0.9750357 0.0249642]]
[[0.7240351  0.27596498]]
[[0.33603266 0.66396743]]
[[9.9902165e-01 9.7837998e-04]]
[[0.07579412 0.92420584]]
[[0.8975549 0.1024451]]
[[0.3646567 0.6353433]]
[[0.43259194 0.5674081 ]]
[[9.999995e-01 4.208133e-07]]
[[0.6756364  0.32436356]]
[[0.9974485  0.00255145]]
[[2.8243364e-04 9.9971753e-01]]
[[0.02849144 0.97150856]]
[[0.3552298  0.64477026]]
[[0.10818205 0.8918179 ]]
[[0.38236    0.61763996]]
[[8.182395e-04 9.991817e-01]]
[[9.9961346e-01 3.8659730e-04]]
[[6.806301e-11 1.000000e+00]]
[[0.77076536 0.22923467]]
[[0.80317914 0.19682081]]
[[9.999994e-01 5.922692e-07]]
[[0.17251979 0.8274802 ]]
[[0.99877614 0.00122384]]
[[0.08333788 0.91666216]]
[[0.40396413 0.59603584]]
[[1.0000000e+00 2.0604067e-09]]
[[0.17597692 0.8240231 ]]
[[0.45609713 0.5439029 ]]
[[0.00798952 0.9920105 ]]
[[0.00174639 0.99825364]]
[[0.63902164 0.36097842]]
[[1.0000000e+00 9.6794714e-09]]
[[0.07355026 0.9264498 ]]
[[0.06107814 0.93892187]]
[[0.9409538  0.05904619]]
[[0.972691 0.027309]]
[[