In [1]:
import tensorflow as tf
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dropout,Input,Flatten,Dense,MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator  # Data Augumentation

In [ ]:
tf.test.is_gpu_available()

In [ ]:
tf.config.list_physical_devices('GPU')

In [3]:
batchsize=8

In [4]:
train_datagen= ImageDataGenerator(rescale=1./255, rotation_range=0.2,shear_range=0.2,
    zoom_range=0.2,width_shift_range=0.2,
    height_shift_range=0.2, validation_split=0.2)

train_data= train_datagen.flow_from_directory(r'C:\Users\abirr\Desktop\New folder (2)\updatedataset\train',
                                target_size=(80,80),batch_size=batchsize,class_mode='categorical',subset='training' )

validation_data= train_datagen.flow_from_directory(r'C:\Users\abirr\Desktop\New folder (2)\updatedataset\train',
                                target_size=(80,80),batch_size=batchsize,class_mode='categorical', subset='validation')

Found 54334 images belonging to 2 classes.
Found 13583 images belonging to 2 classes.


In [5]:
test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_directory(r'C:\Users\abirr\Desktop\New folder (2)\updatedataset\test',
                                target_size=(80,80),batch_size=batchsize,class_mode='categorical')

Found 16981 images belonging to 2 classes.


In [6]:
bmodel = InceptionV3(include_top=False, weights='imagenet', input_tensor=Input(shape=(80,80,3)))
hmodel = bmodel.output
hmodel = Flatten()(hmodel)
hmodel = Dense(64, activation='relu')(hmodel)
hmodel = Dropout(0.5)(hmodel)
hmodel = Dense(2,activation= 'softmax')(hmodel)

model = Model(inputs=bmodel.input, outputs= hmodel)
for layer in bmodel.layers:
    layer.trainable = False

In [ ]:
model.summary()

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint,EarlyStopping, ReduceLROnPlateau

In [ ]:
checkpoint = ModelCheckpoint(r'C:\Users\abirr\Desktop\New folder (2)\Driver-Drowsiness-Detection-using-Deep-Learning-main\saved model\model.h5',
                            monitor='val_loss',save_best_only=True,verbose=3)

earlystop = EarlyStopping(monitor = 'val_loss', patience=7, verbose= 3, restore_best_weights=True)

learning_rate = ReduceLROnPlateau(monitor= 'val_loss', patience=3, verbose= 3, )

callbacks=[checkpoint,earlystop,learning_rate]

In [ ]:
model.compile(optimizer='Adam', loss='categorical_crossentropy',metrics=['accuracy'])

model.fit_generator(train_data,steps_per_epoch=train_data.samples//batchsize,
                   validation_data=validation_data,
                   validation_steps=validation_data.samples//batchsize,
                   callbacks=callbacks,
                    epochs=20)

In [ ]:
# Model Evaluation

In [ ]:
acc_tr, loss_tr = model.evaluate_generator(train_data)
print(acc_tr)
print(loss_tr)

In [ ]:
acc_vr, loss_vr = model.evaluate_generator(validation_data)
print(acc_vr)
print(loss_vr)

In [ ]:
acc_test, loss_test = model.evaluate_generator(test_data)
print(acc_tr)
print(loss_tr)

In [7]:
from keras.models import load_model



# returns a compiled model
# identical to the previous one
model = load_model('model.h5')

In [8]:
# Path to your folder testing data
testing_folder = r"C:\Users\abirr\Desktop\New folder (2)\updatedataset\test"
# Image size (set up the image size used for training)
img_size = 80
# Batch size (you should tune it based on your memory)
batch_size = 16

val_datagen = ImageDataGenerator(
    rescale=1. / 255)
validation_generator = val_datagen.flow_from_directory(
    testing_folder,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    shuffle=False,
    class_mode='categorical')

Found 16981 images belonging to 2 classes.


In [ ]:
# Number of steps corresponding to an epoch
steps = 100
predictions = model.predict(validation_generator, steps=steps)

In [ ]:
predictions

In [ ]:
x = len(predictions)

In [ ]:
x

In [17]:
import numpy as np


In [ ]:
val_preds = np.argmax(predictions, axis=-1)
val_trues = validation_generator.classes
cm = metrics.confusion_matrix(val_trues, val_preds)

In [ ]:
import sklearn.metrics as metrics


In [68]:
test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_directory(r'C:\Users\abirr\Desktop\New folder (2)\updatedataset\test',
                                target_size=(80,80),batch_size=batchsize,class_mode='categorical')

Found 16981 images belonging to 2 classes.


In [30]:

y_true  = np.array(y_true)

In [31]:
y_true = np.array_str(y_true)

In [36]:
y_true =y_true.replace("0","close")
y_true =y_true.replace("1","open")

In [37]:
y_true

'[close close close ... open open open]'

In [45]:
y_pred = model.predict(test_data)

In [52]:
y_pred = (y_pred > 0.3) 




In [54]:
y_clo=y_pred[:,0]

In [57]:
y_clo

'[ True False  True ...  True False False]'

In [56]:
y_clo = np.array_str(y_clo)

In [58]:
y_clo =y_clo.replace("True","close")
y_clo =y_clo.replace("False","open")

In [62]:
arr = y_clo.split()

In [64]:
arr1 = y_true.split()

IndexError: tuple index out of range

In [65]:
arr1

['[close', 'close', 'close', '...', 'open', 'open', 'open]']

In [66]:
from sklearn.metrics import classification_report

print(classification_report(arr, arr1))

ValueError: Found input variables with inconsistent numbers of samples: [8, 7]

In [75]:
from sklearn.metrics import classification_report
y_true = validation_generator.classes
y_pred = model.predict(test_data)

In [76]:
y_true

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
 = np.where(close1 == True, "close", close1)

In [ ]:
y_pred=y_pred[:,1]

In [ ]:
y_pred

In [ ]:
y_pred = y_pred.astype('int32')

In [ ]:
import sklearn.metrics
print('Confusion Matrix')
print(confusion_matrix(y_true, y_pred))

In [ ]:
y_true

In [72]:
from sklearn.metrics import classification_report

y_true = validation_generator.classes
y_pred = model.predict(test_data)
y_pred=np.round(abs(y_pred))
y_pred = (y_pred > 0.3)


In [73]:
y_pred

array([[False,  True],
       [False,  True],
       [ True, False],
       ...,
       [ True, False],
       [ True, False],
       [ True, False]])

In [ ]:
y_pred

In [ ]:
y_pred

In [74]:
y_true

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
img_path = r'C:\Users\abirr\Desktop\New folder (2)\updatedataset\train\close\s0001_00002_0_0_0_0_0_01.png'

img = image.load_img(img_path, target_size=(80, 80))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
plt.imshow(img)

In [ ]:
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input

In [ ]:
features 

In [ ]:
 y_pred[:,0]

In [ ]:
import sklearn.metrics
r = sklearn.metrics.confusion_matrix(y_true, y_pred)
print(r)

In [ ]:
import seaborn as sn
sn.heatmap(r, annot=True)

In [ ]:
from keras.models import load_model
import cv2
import numpy as np

model = load_model('model.h5')

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

img = cv2.imread(r'C:\Users\abirr\Desktop\New folder (2)\updatedataset\train\close\s0001_00002_0_0_0_0_0_01.png')
img = cv2.resize(img,(80,80))
img = np.reshape(img,[1,80,80,3])

classes = model.predict_classes(img)

print (classes)

In [ ]:
np.reshape(clos, (2, 3))